### ISSUE TITLE
Error: Cannot find module '@google-cloud/common' with 0.18.0 and 0.18.1

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/nodejs-common#120] opened 2018-04-30 16:39 UTC
#### Environment details

  - OS: Linux (also seen on appveyor, so impacts windows)
  - Node.js version: 8.11.1 (also seen w/ latest version of 6 and 9)
  - npm version: 5.8.0
  - @google-cloud/common version: 0.18.0 (and 0.18.1)

#### Steps to reproduce

  1. npm install @google-cloud/common
  2. Run a test (or anything else probably) which requires `@google-cloud/common`

Then seen this error message (with a stack trace):
```
Error: Cannot find module '@google-cloud/common'
```

When I run `ls node_modules/@google-cloud/common/` I see `CONTRIBUTORS  LICENSE  node_modules  package.json  README.md`. So there don't seem to be any .js files in the package I've installed.

**Comment by aalexand** [comment] 2018-04-30 17:07
@nolanmar511 Bullet 2 in "Steps to reproduce" seems to be unfinished.

**Comment by JustinBeckwith** [comment] 2018-04-30 17:44
Apologies for the trouble.  This was fixed in `0.18.2` 😄

**Closed by JustinBeckwith** 2018-04-30 17:44 UTC
