### ISSUE TITLE
[NPM ERROR] Interface 'ServiceOptions' incorrectly extends interface

### ISSUE THREAD

**Issue by zubairzahoor** [googleapis/nodejs-common#734] opened 2022-02-23 06:07 UTC
Since today, I am unable to build my project with this error. Nothing changed from our side,
 
 Types of property 'authClient' are incompatible.
11:08:51      Type 'GoogleAuth<JSONClient> | undefined' is not assignable to type 'JSONClient | undefined'.
11:08:51  node_modules/@google-cloud/common/build/src/util.d.ts(42,18): error TS2430: Interface 'MakeAuthenticatedRequestFactoryConfig' incorrectly extends interface 'GoogleAuthOptions<JSONClient>'.
11:08:51    Types of property 'authClient' are incompatible.
11:08:51      Type 'GoogleAuth<JSONClient> | undefined' is not assignable to type 'JSONClient | undefined'.
11:08:51        Type 'GoogleAuth<JSONClient>' is not assignable to type 'JSONClient | undefined'.
11:08:51          Type 'GoogleAuth<JSONClient>' is missing the following properties from type 'JWT': createScoped, getRequestMetadataAsync, fetchIdToken, hasUserScopes

#### Environment details

  - OS: CentOS
  - Node.js version: NodeJS_v12.18.2
  - `@google-cloud/common` version: 3.9.0

#### Steps to reproduce

 A simple npm run build causes this.

**Comment by zubairzahoor** [comment] 2022-02-23 10:21
This is most likely an issue with google-auth-library that was updated yesterday.
Issue here: https://github.com/googleapis/google-auth-library-nodejs/issues/1374

**Comment by finallyRaunak** [comment] 2022-02-23 10:42
> This is most likely an issue with google-auth-library that was updated yesterday. Issue here: [googleapis/google-auth-library-nodejs#1374](https://github.com/googleapis/google-auth-library-nodejs/issues/1374)

Yes, I also think the same, having the same issue with `@google-cloud/logging-winston` package which uses `google-auth-library`

**Comment by bcoe** [comment] 2022-02-23 15:05
👋 for folks having issues, could you provide the output of `npm ls google-auth-library`, a new version of the auth library was released yesterday, but the current `latest` version of the library remained `7.12.0`. So, I'm not sure how npm would be pulling in `7.14.0`.

**Comment by bcoe** [comment] 2022-02-23 15:13
@SametSahin10 @zubairzahoor follow up question, what `@google-cloud` library are you using?

**Comment by SametSahin10** [comment] 2022-02-23 15:15
> wave for folks having issues, could you provide the output of `npm ls google-auth-library`, a new version of the auth library was released yesterday, but the current `latest` version of the library remained `7.12.0`. So, I'm not sure how npm would be pulling in `7.14.0`.

Output of `npm ls google-auth-library`:

functions@ /home/sametsahin/work/firebase-projects/flambu/functions
└─┬ firebase-admin@10.0.2
  ├─┬ @google-cloud/firestore@4.15.1
  │ └─┬ google-gax@2.30.0
  │   └── google-auth-library@7.14.0 deduped
  └─┬ @google-cloud/storage@5.18.2
    ├─┬ @google-cloud/common@3.9.0
    │ └── google-auth-library@7.14.0 deduped
    └── google-auth-library@7.14.0

**Comment by SametSahin10** [comment] 2022-02-23 15:16
> @SametSahin10 @zubairzahoor follow up question, what `@google-cloud` library are you using?

Does my last comment answer this as well?

**Comment by bcoe** [comment] 2022-02-23 15:20
@SametSahin10 @zubairzahoor if you remove your `package-lock.json` and reinstall, you should stop seeing a build error.

I'm keeping this open until the problem is fixed, for now I just rolled back `google-gax`, which is the dependency forcing `7.14.0` of the auth library.

**Comment by danielbankhead** [comment] 2022-02-23 16:00
Hey everyone! Apologies for the broken builds; the type-related issues should now be resolved via (`nodejs-common` `v3.10.0`) https://github.com/googleapis/nodejs-common/pull/733.

**Comment by bcoe** [comment] 2022-02-23 16:11
@danielbankhead I think because of the collision on the key-name `authClient` we should call the update to GoogleAuth breaking, or else folks could end up with trees that can't compile.

What do you think?

**Comment by danielbankhead** [comment] 2022-02-23 21:10
[_Synced offline, sharing here for visibility_]

I think we should be fine, `nodejs-common` is the only library in [`googleapis`](https://github.com/googleapis) with the name collision (others use the conventional `auth` param) - and is the only library with issues with the updated auth library.

https://github.com/googleapis/nodejs-common/pull/733 should resolve this, however I'll keep this open and monitor over the next few days.

**Comment by finallyRaunak** [comment] 2022-02-24 04:37
> 👋 for folks having issues, could you provide the output of `npm ls google-auth-library`, a new version of the auth library was released yesterday, but the current `latest` version of the library remained `7.12.0`. So, I'm not sure how npm would be pulling in `7.14.0`.

@bcoe : Here is the output 

  ├─┬ @google-cloud/logging-winston@4.1.2
  │ └── google-auth-library@7.14.0
  ├─┬ @google-cloud/logging@9.7.0
  │ ├─┬ @google-cloud/common@3.9.0
  │ │ └── google-auth-library@7.14.0 deduped
  │ ├── google-auth-library@7.14.0 deduped
  │ └─┬ google-gax@2.30.0
  │   └── google-auth-library@7.14.0 deduped
  └─┬ @google-cloud/storage@5.18.2
    └── google-auth-library@7.14.0 deduped

**Comment by ederius100** [comment] 2022-02-24 14:14
Hi guys, me output
│ └─┬ ***@***.***
│   ├─┬ @***@***.***
│   │ └─┬ ***@***.***
│   │   └── ***@***.*** deduped
│   └─┬ @***@***.***
│     ├─┬ @***@***.***
│     │ └── ***@***.***
│     └── ***@***.*** deduped
└─┬ ***@***.***
  ├─┬ @***@***.***
  │ ├── ***@***.***
  │ └─┬ ***@***.***
  │   └── ***@***.*** deduped
  └── ***@***.***


Looks like when google-auth-library is a dependency of ***@***.*** is
installing ***@***.*** Good luck!

**Comment by danielbankhead** [comment] 2022-02-25 16:53
Things are looking stable as of `@google-cloud/common@3.10.0` -  closing. https://github.com/googleapis/nodejs-common/pull/733.

**Closed by danielbankhead** 2022-02-25 16:53 UTC
Labels: type: bug, priority: p1

**Comment by appfrilans** [comment] 2022-03-10 10:14
I still have a similar issue.

```
node_modules/@google-cloud/common/build/src/service.d.ts:29:18 - error TS2430: Interface 'ServiceOptions' incorrectly extends interface 'GoogleAuthOptions<JSONClient>'.
  Types of property 'authClient' are incompatible.
    Type 'GoogleAuth<JSONClient> | undefined' is not assignable to type 'JWT | UserRefreshClient | Impersonated | BaseExternalAccountClient | undefined'.
      Type 'GoogleAuth<JSONClient>' is not assignable to type 'JWT | UserRefreshClient | Impersonated | BaseExternalAccountClient | undefined'.
        Type 'GoogleAuth<JSONClient>' is not assignable to type 'JWT'.

29 export interface ServiceOptions extends GoogleAuthOptions {
                    ~~~~~~~~~~~~~~

node_modules/@google-cloud/common/build/src/util.d.ts:42:18 - error TS2430: Interface 'MakeAuthenticatedRequestFactoryConfig' incorrectly extends interface 'GoogleAuthOptions<JSONClient>'.
  Types of property 'authClient' are incompatible.
    Type 'GoogleAuth<JSONClient> | undefined' is not assignable to type 'JWT | UserRefreshClient | Impersonated | BaseExternalAccountClient | undefined'.
      Type 'GoogleAuth<JSONClient>' is not assignable to type 'JWT | UserRefreshClient | Impersonated | BaseExternalAccountClient | undefined'.
        Type 'GoogleAuth<JSONClient>' is missing the following properties from type 'JWT': createScoped, getRequestMetadataAsync, fetchIdToken, hasUserScopes, and 53 more.

42 export interface MakeAuthenticatedRequestFactoryConfig extends GoogleAuthOptions {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Using Firebase Functions with typeScript. Using the following imports:

```
import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
import * as geofire from "geofire-common";
import * as key from './service-account-key.json';
import { google } from 'googleapis';
```

Running ´npm ls google-auth-library´ gives me:
`└── (empty)`

Tried updating all npm's to latest version. My package.json looks like this:

```
{
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts .",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@google-cloud/logging": "^9.8.0",
    "date-fns": "^2.28.0",
    "dateformat": "^5.0.2",
    "firebase": "^9.6.8",
    "firebase-admin": "^9.8.0",
    "firebase-functions": "^3.18.1",
    "geofire-common": "^5.2.0",
    "googleapis": "^96.0.0",
    "request": "^2.88.2"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.9.1",
    "@typescript-eslint/parser": "^3.8.0",
    "eslint": "^7.6.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-promise": "^6.0.0",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^3.8.0"
  },
  "private": true
}

```

**Comment by bcoe** [comment] 2022-03-24 15:39
@appfrilans could I bother you to `rm package-lock.json`, and to reinstall. My guess is you're still on an older version of the auth library.

**Comment by bcoe** [comment] 2022-03-24 15:43
@appfrilans great, sorry for the slow response I'm glad you're unblocked 👍

**Comment by b2m9** [comment] 2022-03-28 10:05
For people who arrive here wondering why they can't deploy new Firebase Cloud Functions anymore:

It seems to me that `firebase-admin@10.0.2` requires `@google-cloud/storage@5.3.0` which requires `@google-cloud/common@3.6.0`.

For everyone looking to resolve that without using `skipLibCheck:true`, run `npm install @google-cloud/common@3.10.0` and you should be able to deploy your Cloud Functions again.
